UPDATE ai_agents SET comment = 'Garrick Padfoot - Cast \'Defensive Stance\'' WHERE entry = 103 AND spell = 7164;
UPDATE ai_agents SET comment = 'Surena Caledon - Cast \'Fireball\'' WHERE entry = 881 AND spell = 20793;
UPDATE ai_agents SET comment = 'Surena Caledon - Cast \'Frost Armor\'' WHERE entry = 881 AND spell = 12544;
UPDATE ai_agents SET comment = 'Riverpaw Outrunner - Cast \'Thrash\'' WHERE entry = 478 AND spell = 3391;
UPDATE ai_agents SET comment = 'Kobold Geomancer - Cast \'Fireball\'' WHERE entry = 476 AND spell = 20793;
UPDATE ai_agents SET comment = 'Kobold Geomancer - Cast \'Frost Armor\'' WHERE entry = 476 AND spell = 12544;
UPDATE ai_agents SET comment = 'Defias Rogue Wizard - Cast \'Frostbolt\'' WHERE entry = 474 AND spell = 13322;
UPDATE ai_agents SET comment = 'Defias Rogue Wizard - Cast \'Frost Armor\'' WHERE entry = 474 AND spell = 12544;
UPDATE ai_agents SET comment = 'Defias Bandit - Cast \'Snap Kick\'' WHERE entry = 116 AND spell = 8646;
UPDATE ai_agents SET comment = 'Defias Dockworker - Cast \'Snap Kick\'' WHERE entry = 6927 AND spell = 8646;
UPDATE ai_agents SET comment = 'Defias Bodyguard - Cast \'Backstab\'' WHERE entry = 6866 AND spell = 7159;
UPDATE ai_agents SET comment = 'Defias Bodyguard - Cast \'Disarm\'' WHERE entry = 6866 AND spell = 6713;
UPDATE ai_agents SET comment = 'Hogger - Cast \'Rushing Charge\'' WHERE entry = 448 AND spell = 6268;
UPDATE ai_agents SET comment = 'Hogger - Cast \'Pierce Armor\'' WHERE entry = 448 AND spell = 6016;
UPDATE ai_agents SET comment = 'Hogger - Cast \'Head Butt\'' WHERE entry = 448 AND spell = 6730;
UPDATE ai_agents SET comment = 'Narg the Taskmaster - Cast \'Battle Shout\'' WHERE entry = 79 AND spell = 9128;
UPDATE ai_agents SET comment = 'Murloc Forager - Cast \'Drink Minor Potion\'' WHERE entry = 46 AND spell = 3368;
UPDATE ai_agents SET comment = 'Murloc Lurker - Cast \'Backstab\'' WHERE entry = 732 AND spell = 7159;
UPDATE ai_agents SET comment = 'Ruklar the Trapper - Cast \'Pierce Armor\'' WHERE entry = 60 AND spell = 6016;
UPDATE ai_agents SET comment = 'Ruklar the Trapper - Cast \'Net\'' WHERE entry = 60 AND spell = 12024;
UPDATE ai_agents SET comment = 'Kobold Miner - Cast \'Pierce Armor\'' WHERE entry = 40 AND spell = 6016;
UPDATE ai_agents SET comment = 'Fedfennel - Cast \'Demoralizing Shout\'' WHERE entry = 472 AND spell = 13730;
UPDATE ai_agents SET comment = 'Fedfennel - Cast \'Nimble Reflexes\'' WHERE entry = 472 AND spell = 3238;
UPDATE ai_agents SET comment = 'Stonetusk Boar - Cast \'Rushing Charge\'' WHERE entry = 113 AND spell = 6268;
UPDATE ai_agents SET comment = 'Longsnout - Cast \'Rushing Charge\'' WHERE entry = 119 AND spell = 6268;
UPDATE ai_agents SET comment = 'Princess - Cast \'Rushing Charge\'' WHERE entry = 330 AND spell = 6268;
UPDATE ai_agents SET comment = 'Porcine Entourage - Cast \'Rushing Charge\'' WHERE entry = 390 AND spell = 6268;
UPDATE ai_agents SET comment = 'Stonetusk Boar - Cast \'Rushing Charge\'' WHERE entry = 524 AND spell = 6268;
UPDATE ai_agents SET comment = 'Morgan the Collector - Cast \'Backstab\'' WHERE entry = 473 AND spell = 7159;
UPDATE ai_agents SET comment = 'Morgaine the Sly - Cast \'Backstab\'' WHERE entry = 99 AND spell = 7159;
UPDATE ai_agents SET comment = 'Morgaine the Sly - Cast \'Poison\'' WHERE entry = 99 AND spell = 11918;
UPDATE ai_agents SET comment = 'Gruff Swiftbyte - Cast \'Thrash\'' WHERE entry = 100 AND spell = 3391;
UPDATE ai_agents SET comment = 'Mother Fang - Cast \'Poison\'' WHERE entry = 471 AND spell = 11918;
UPDATE ai_agents SET comment = 'Mother Fang - Cast \'Web\'' WHERE entry = 471 AND spell = 12023;
UPDATE ai_agents SET comment = 'Mine Spider - Cast \'Poison\'' WHERE entry = 43 AND spell = 11918;
UPDATE ai_agents SET comment = 'Forest Spider - Cast \'Poison\'' WHERE entry = 30 AND spell = 11918;