SET @SPID := 9145;

DELETE FROM creature_waypoints WHERE spawnid = @SPID;

REPLACE INTO `creature_waypoints` (`spawnid`, `waypointid`, `position_x`, `position_y`, `position_z`, `waittime`, `flags`, `forwardemoteoneshot`, `forwardemoteid`, `backwardemoteoneshot`, `backwardemoteid`, `forwardskinid`, `backwardskinid`) VALUES (@SPID, 1, -5178.46, 608.044, 408.965, 5000, 0, 0, 0, 0, 0, 0, 0);
REPLACE INTO `creature_waypoints` (`spawnid`, `waypointid`, `position_x`, `position_y`, `position_z`, `waittime`, `flags`, `forwardemoteoneshot`, `forwardemoteid`, `backwardemoteoneshot`, `backwardemoteid`, `forwardskinid`, `backwardskinid`) VALUES (@SPID, 2, -5188.18, 542.216, 391.373, 0, 0, 0, 0, 0, 0, 0, 0);
REPLACE INTO `creature_waypoints` (`spawnid`, `waypointid`, `position_x`, `position_y`, `position_z`, `waittime`, `flags`, `forwardemoteoneshot`, `forwardemoteid`, `backwardemoteoneshot`, `backwardemoteid`, `forwardskinid`, `backwardskinid`) VALUES (@SPID, 3, -5182.78, 494.009, 387.98, 0, 0, 0, 0, 0, 0, 0, 0);
REPLACE INTO `creature_waypoints` (`spawnid`, `waypointid`, `position_x`, `position_y`, `position_z`, `waittime`, `flags`, `forwardemoteoneshot`, `forwardemoteid`, `backwardemoteoneshot`, `backwardemoteid`, `forwardskinid`, `backwardskinid`) VALUES (@SPID, 4, -5129.79, 449.494, 395.108, 0, 0, 0, 0, 0, 0, 0, 0);
REPLACE INTO `creature_waypoints` (`spawnid`, `waypointid`, `position_x`, `position_y`, `position_z`, `waittime`, `flags`, `forwardemoteoneshot`, `forwardemoteid`, `backwardemoteoneshot`, `backwardemoteid`, `forwardskinid`, `backwardskinid`) VALUES (@SPID, 5, -5098.45, 462.317, 403.873, 5000, 0, 0, 0, 0, 0, 0, 0);
REPLACE INTO `creature_waypoints` (`spawnid`, `waypointid`, `position_x`, `position_y`, `position_z`, `waittime`, `flags`, `forwardemoteoneshot`, `forwardemoteid`, `backwardemoteoneshot`, `backwardemoteid`, `forwardskinid`, `backwardskinid`) VALUES (@SPID, 6, -5129.79, 449.494, 395.108, 0, 0, 0, 0, 0, 0, 0, 0);
REPLACE INTO `creature_waypoints` (`spawnid`, `waypointid`, `position_x`, `position_y`, `position_z`, `waittime`, `flags`, `forwardemoteoneshot`, `forwardemoteid`, `backwardemoteoneshot`, `backwardemoteid`, `forwardskinid`, `backwardskinid`) VALUES (@SPID, 7, -5182.78, 494.009, 387.98, 0, 0, 0, 0, 0, 0, 0, 0);
REPLACE INTO `creature_waypoints` (`spawnid`, `waypointid`, `position_x`, `position_y`, `position_z`, `waittime`, `flags`, `forwardemoteoneshot`, `forwardemoteid`, `backwardemoteoneshot`, `backwardemoteid`, `forwardskinid`, `backwardskinid`) VALUES (@SPID, 8, -5188.18, 542.216, 391.373, 0, 0, 0, 0, 0, 0, 0, 0);